name: Dimond Saints
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55379
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#790004'
    - '#f3f8fc'
    - '#70636c'
    - '#adc5dd'
  brandStrength: 1
  lightness: 0.8409184305928648
  saturation: 0.837063676211983
  rhythmicContrast: 0.2679352043196559
purpose: []
