name: Dimond Saints
favicon: null
layout_spectrum: 0.8324783118441701
typography_spectrum: 0.5373557540588081
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.712912700837478
  lightness: 0.8409184305928648
  saturation: 0.837063676211983
  rhythmicContrast: 0.2679352043196559
purpose: []
